#!/bin/bash

if ! command -v docker &> /dev/null; then
    echo "Error: Docker is not installed. Please install it and try again."
    exit 1
fi

CMD="${@:1}"

if [[ -z "$CMD" ]]; then
    echo "Usage: epitest <command>"
    exit 1
fi

BASE_EXEC_CMD="docker"
DOCKER_SOCKET_PATH=/var/run/docker.sock
HAS_SOCKET_ACCESS=$(test -r $DOCKER_SOCKET_PATH; echo "$?")

if [ $HAS_SOCKET_ACCESS -ne 0 ]; then
    if ! grep -q "^docker:" /etc/group; then
        echo "Creating the 'docker' group..."
        sudo groupadd docker
    fi

    echo "WARNING: Socket access is denied"
    echo "To fix this we will add the current user to docker group with : sudo usermod -a -G docker $USER"
    read -p "Do you want to proceed? (yes/no) " yn
    case $yn in
        yes | Y | y | Yes | YES)
            echo "ok, we will proceed";
            sudo usermod -a -G docker $USER;
            echo "You must reboot your computer for the changes to take effect";;
        no | N | n | No | NO)
            echo "ok, Skipping";;
        *)
            echo "invalid response, Skipping";;
    esac
    BASE_EXEC_CMD="sudo ${BASE_EXEC_CMD}"
fi

IMAGE="epitechcontent/epitest-docker"

if docker image inspect "$IMAGE" &>/dev/null; then
    echo "Checking for updates..."
    docker pull "$IMAGE" | tee pull.log

    if grep -q "Downloaded newer image" pull.log; then
        echo "New image detected. Removing old version..."
        docker image rm "$(docker images -q "$IMAGE")"
    fi

    rm pull.log
else
    echo "Image not found locally. Pulling it for the first time..."
    docker pull "$IMAGE"
fi

docker run --rm -it -v "$(pwd)":/app -w /app "$IMAGE" bash -c "$CMD"
